# Generated by Django 3.2.7 on 2021-10-28 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramientas',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='herramientas',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.clasificacion'),
        ),
    ]
