# Generated by Django 4.0.2 on 2022-02-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20211027_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la unidad')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='herramientas', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('url', models.URLField(null=True, verbose_name='Link del video')),
                ('imagen', models.ImageField(blank=True, upload_to='videos/imagenes', verbose_name='Imagen')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.cursos')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.unidades')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
