# Generated by Django 4.0.2 on 2022-02-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_cursos_unidades_alter_herramientas_imagen_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientas',
            name='archivo',
            field=models.FileField(null=True, upload_to='herramientas/archivos', verbose_name='Archivo'),
        ),
    ]
