# Generated by Django 4.0.2 on 2022-02-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_herramientas_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='herramientas/archivos', verbose_name='Archivo'),
        ),
    ]
